# Generated by Django 4.0.3 on 2022-04-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tasks', 'verbose_name_plural': 'Task'},
        ),
    ]
