# Generated by Django 4.0.3 on 2022-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('task', models.TextField(verbose_name='Caption')),
                ('image', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Task2',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tasks', 'verbose_name_plural': 'Task1'},
        ),
    ]
