# Generated by Django 4.0.3 on 2022-04-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tasks_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('task', models.TextField(verbose_name='Caption')),
                ('image', models.ImageField(upload_to='maim/static/img/')),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Task3',
            },
        ),
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(upload_to='maim/static/img/'),
        ),
    ]
