# Generated by Django 4.0.3 on 2022-04-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task2_alter_tasks_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task_new',
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AlterModelOptions(
            name='task_new',
            options={'verbose_name': 'Tasks', 'verbose_name_plural': 'Task'},
        ),
    ]
