# Generated by Django 4.0.3 on 2022-04-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_task_task_new_delete_task2_delete_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('task', models.TextField(verbose_name='Caption')),
                ('image', models.FileField(upload_to='static/main/')),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Task',
            },
        ),
        migrations.DeleteModel(
            name='Task_new',
        ),
    ]
