# Generated by Django 4.0.3 on 2022-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_free_delete_task_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_fre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('task', models.TextField(verbose_name='Caption')),
                ('task_img', models.ImageField(upload_to='main/static/main/img/')),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Task',
            },
        ),
        migrations.DeleteModel(
            name='Task_free',
        ),
    ]
